## Practice Questions for Pandas

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

3. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
```

4. Create a 4x4 NumPy array filled with random integers between 1 and 100. Then, reshape this array into two separate 2D arrays, where one represents the rows and the other represents the columns. Write a function, preferably using a lambda function, to calculate the sum of each row and each column separately, and return the results as two separate NumPy arrays
```


In [25]:
import pandas as pd

In [26]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [27]:
# Extract 'Manufacturer', 'Model', and 'Type' columns for every 20th row starting from the 1st row (row 0)
result_df = df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]

# Display the result
print(result_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [28]:
# Calculate the mean for 'Min.Price' and 'Max.Price' columns
min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()

# Use loc or iloc to avoid chained assignment
df.loc[:, 'Min.Price'] = df['Min.Price'].fillna(min_price_mean)
df.loc[:, 'Max.Price'] = df['Max.Price'].fillna(max_price_mean)

# Display the DataFrame with missing values replaced
print(df[['Min.Price', 'Max.Price']])

    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]


In [30]:
# Create a DataFrame
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4), columns=['L', 'A', 'Y', 'Z'])

# Filter rows with row sum greater than 100
result_df = df[df.sum(axis=1) > 100]

# Display the result
print(result_df)

     L   A   Y   Z
7   38  32  34  34
12  12  39  33  18
14  38  34  25  26


In [33]:
import numpy as np

# Create a 4x4 NumPy array with random integers between 1 and 100
random_array = np.random.randint(1, 101, (4, 4))

# Reshape the array into two separate 2D arrays for rows and columns
rows_array = random_array.reshape(2, 8)
columns_array = random_array.T.reshape(2, 8)

# Define a lambda function to calculate the sum of each row
sum_row = lambda x: np.sum(x, axis=1)

# Define a lambda function to calculate the sum of each column
sum_column = lambda x: np.sum(x, axis=0)

# Calculate the sum of each row and each column using the lambda functions
sum_of_rows = sum_row(rows_array)
sum_of_columns = sum_column(columns_array)

# Display the original array and the results
print("Original Array:")
print(random_array)
print("\nRows Array:")
print(rows_array)
print("\nColumns Array:")
print(columns_array)
print("\nSum of Each Row:")
print(sum_of_rows)
print("\nSum of Each Column:")
print(sum_of_columns)

Original Array:
[[98 99 88  3]
 [71 14 21 29]
 [46  5 91 46]
 [80 75 16 12]]

Rows Array:
[[98 99 88  3 71 14 21 29]
 [46  5 91 46 80 75 16 12]]

Columns Array:
[[98 71 46 80 99 14  5 75]
 [88 21 91 16  3 29 46 12]]

Sum of Each Row:
[423 371]

Sum of Each Column:
[186  92 137  96 102  43  51  87]
